-- MySQL Script generated by MySQL Workbench
-- Tue Oct  5 11:11:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_type` (
  `id` INT NOT NULL,
  `user_typecol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_accounts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_type_id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `user_email` VARCHAR(255) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `gender` VARCHAR(1) NOT NULL,
  `contact_number` INT NOT NULL,
  `user_img` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `user_type_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_user_account_user_type1_idx` (`user_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_account_user_type1`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `mydb`.`user_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recruter_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recruter_types` (
  `id` INT NOT NULL,
  `business_stream_name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recruter_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recruter_account` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`companies` (
  `id` INT NOT NULL,
  `stream_type_id` INT NOT NULL,
  `company_name` VARCHAR(45) NOT NULL,
  `profile_description` VARCHAR(2000) NOT NULL,
  `establishment_date` DATE NOT NULL,
  `company_website_url` VARCHAR(500) NOT NULL,
  `company_img` BLOB NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `stream_type_id_idx` (`stream_type_id` ASC) VISIBLE,
  CONSTRAINT `stream_type_id`
    FOREIGN KEY (`stream_type_id`)
    REFERENCES `mydb`.`recruter_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`company_img`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`company_img` (
  `id` INT NOT NULL,
  `Company_imgcol` BLOB NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `company_name`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`locations` (
  `id` INT NOT NULL,
  `adress` VARCHAR(100) NULL,
  `city` VARCHAR(60) NULL,
  `region` VARCHAR(50) NULL,
  `country` VARCHAR(50) NULL,
  `zip_code` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`seeker_profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`seeker_profiles` (
  `user_account_id` INT NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `locations_id` INT NOT NULL,
  PRIMARY KEY (`user_account_id`, `locations_id`),
  INDEX `fk_seeker_profiles_locations1_idx` (`locations_id` ASC) VISIBLE,
  CONSTRAINT `user_account_id`
    FOREIGN KEY (`user_account_id`)
    REFERENCES `mydb`.`user_accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seeker_profiles_locations1`
    FOREIGN KEY (`locations_id`)
    REFERENCES `mydb`.`locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`skill_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`skill_details` (
  `id` INT NOT NULL,
  `skill_detail_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`seeker_skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`seeker_skills` (
  `user_account_id` INT NOT NULL,
  `skill_id` INT NOT NULL,
  `skill_level` INT NOT NULL,
  PRIMARY KEY (`skill_id`, `user_account_id`),
  INDEX `skill_id_idx` (`skill_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_account_id`)
    REFERENCES `mydb`.`seeker_profiles` (`user_account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `skill_id`
    FOREIGN KEY (`skill_id`)
    REFERENCES `mydb`.`skill_details` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`job_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`job_types` (
  `id` INT NOT NULL,
  `job_type` VARCHAR(35) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`job_posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`job_posts` (
  `id` INT NOT NULL,
  `posted_by_id` INT NOT NULL,
  `job_type_id` INT NOT NULL,
  `company_id` INT NOT NULL,
  `created_date` DATE NOT NULL,
  `job_description` VARCHAR(500) NULL,
  `locations_id` INT NOT NULL,
  PRIMARY KEY (`id`, `locations_id`),
  INDEX `job_post_id_idx` (`job_type_id` ASC) VISIBLE,
  INDEX `company_id_idx` (`company_id` ASC) VISIBLE,
  INDEX `posted_by_id_idx` (`posted_by_id` ASC) VISIBLE,
  INDEX `fk_job_posts_locations1_idx` (`locations_id` ASC) VISIBLE,
  CONSTRAINT `job_post_id`
    FOREIGN KEY (`job_type_id`)
    REFERENCES `mydb`.`job_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `company_id`
    FOREIGN KEY (`company_id`)
    REFERENCES `mydb`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `posted_by_id`
    FOREIGN KEY (`posted_by_id`)
    REFERENCES `mydb`.`user_accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_job_posts_locations1`
    FOREIGN KEY (`locations_id`)
    REFERENCES `mydb`.`locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`job_post_activity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`job_post_activity` (
  `user_account_id` INT NOT NULL,
  `job_post_id` INT NOT NULL,
  `apply_date` DATE NULL,
  PRIMARY KEY (`user_account_id`, `job_post_id`),
  INDEX `job_post_id_idx` (`job_post_id` ASC) VISIBLE,
  CONSTRAINT `user_id2`
    FOREIGN KEY (`user_account_id`)
    REFERENCES `mydb`.`user_accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `job_id_post`
    FOREIGN KEY (`job_post_id`)
    REFERENCES `mydb`.`job_posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`job_post_skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`job_post_skills` (
  `skill_id` INT NOT NULL,
  `job_post_id` INT NOT NULL,
  `skill_level` INT NOT NULL,
  PRIMARY KEY (`skill_id`, `job_post_id`),
  INDEX `job_post_id_idx` (`job_post_id` ASC) VISIBLE,
  CONSTRAINT `skill_id1`
    FOREIGN KEY (`skill_id`)
    REFERENCES `mydb`.`skill_details` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `job_post_id2`
    FOREIGN KEY (`job_post_id`)
    REFERENCES `mydb`.`job_posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`messages` (
  `exp_id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `messages` VARCHAR(3000) NOT NULL,
  `exp_name` VARCHAR(45) NOT NULL,
  `job_posts_id` INT NOT NULL,
  `job_posts_locations_id` INT NOT NULL,
  PRIMARY KEY (`exp_id`, `job_posts_id`, `job_posts_locations_id`),
  INDEX `fk_messages_job_posts1_idx` (`job_posts_id` ASC, `job_posts_locations_id` ASC) VISIBLE,
  CONSTRAINT `exp_id`
    FOREIGN KEY (`exp_id`)
    REFERENCES `mydb`.`user_accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_messages_job_posts1`
    FOREIGN KEY (`job_posts_id` , `job_posts_locations_id`)
    REFERENCES `mydb`.`job_posts` (`id` , `locations_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
